apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-deployment
spec:
  template:
    metadata:
      name: benchmark-pod
    spec:
      restartPolicy: Never
      containers:
        - name: benchmarks
          image: igorzg/typeix-benchmarks:1.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "2000m"
